In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')
%matplotlib inline

import json
import simplejson
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from wordcloud import WordCloud, ImageColorGenerator, STOPWORDS
from PIL import Image

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [34]:
# combine data
movie_credit = pd.concat([movies, credits], axis = 1)
# delete data
delete_column = ["homepage", "id", "original_language", "overview", "production_countries", "spoken_languages", "status", "title", "tagline", "movie_id"]
movie_credit.drop(delete_column, axis = 1, inplace = True)
# show
movie_credit

,budget,genres,keywords,original_title,popularity,production_companies,release_date,revenue,runtime,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",2009-12-10,2787965087,162.0,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2007-05-19,961000000,169.0,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2015-10-26,880674609,148.0,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2012-07-16,1084939099,165.0,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,284139100,132.0,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...","[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",Spider-Man 3,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2007-05-01,890871626,139.0,5.9,3576,"[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...","[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",Tangled,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2010-11-24,591794936,100.0,7.4,3330,"[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",Avengers: Age of Ultron,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...",2015-04-22,1405403694,141.0,7.3,6767,"[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",Harry Potter and the Half-Blood Prince,98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...",2009-07-07,933959197,153.0,7.4,5293,"[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",Batman v Superman: Dawn of Justice,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...",2016-03-23,873260194,151.0,5.7,7004,"[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."
10,270000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 83, ""name"": ""saving the world""}, {""id""...",Superman Returns,57.925623,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""L...",2006-06-28,391081192,154.0,5.4,1400,"[{""cast_id"": 3, ""character"": ""Superman / Clark...","[{""credit_id"": ""553bef6a9251416874003c8f"", ""de..."
11,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 627, ""name"": ""killing""}, {""id"": 1568, ...",Quantum of Solace,107.928811,"[{""name"": ""Eon Productions"", ""id"": 7576}]",2008-10-30,586090727,106.0,6.1,2965,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""52fe43b29251416c7501aa63"", ""de..."
12,200000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 616, ""name"": ""witch""}, {""id"": 663, ""na...",Pirates of the Caribbean: Dead Man's Chest,145.847379,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2006-06-20,1065659812,151.0,7.0,5246,"[{""cast_id"": 37, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""52fe4211c3a36847f8001873"", ""de..."
13,255000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1556, ""name"": ""texas""}, {""id"": 2673, ""...",The Lone Ranger,49.046956,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2013-07-03,89289910,149.0,5.9,2311,"[{""cast_id"": 4, ""character"": ""Tonto"", ""credit_...","[{""credit_id"": ""52fe4928c3a36847f818be95"", ""de..."
14,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 83, ""name"": ""saving the world""}, {""id""...",Man of Steel,99.398009,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",2013-06-12,662845518,143.0,6.5,6359,"[{""cast_id"": 2, ""character"": ""Clark Kent / Kal...","[{""credit_id"": ""52fe4799c3a36847f813e667"", ""de..."
15,225000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 10751...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",The Chronicles of Narnia: Prince Caspian,53.978602,"[{""name"": ""Walt Disney"", ""id"": 5888}, {""name"":...",2008-05-15,419651413,150.0,6.3,1630,"[{""cast_id"": 1, ""character"": ""Prince Caspian"",...","[{""credit_id"": ""55a239e69251412979002e8b"", ""de..."
16,220000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",The Avengers,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",2012-04-25,1519557910,143.0,7.4,11776,"[{""cast_id"": 46, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""52fe4495c3a368484e02b1cf"", ""de..."
17,380000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 658, ""name"": ""sea""}, {""id"": 1316, ""nam...",Pirates of the Caribbean: On Stranger Tides,135.413856,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",2011-05-14,1045713802,136.0,6.4,4948,"[{""cast_id"": 15, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""566b4f54c3a3683f56005151"", ""de..."
18,225000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...","[{""id"": 4379, ""name"": ""time travel""}, {""id"": 5...",Men in Black 3,52.035179,"[{""name"": ""Amblin Entertainment"", ""id"": 56}, {...",2012-05-23,624026776,106.0,6.2,4160,"[{""cast_id"": 4, ""character"": ""Agent J"", ""credi...","[{""credit_id"": ""52fe45b7c3a36847f80d68c7"", ""de..."
19,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 417, ""name"": ""corruption""}, {""id"": 603...",The Hobbit: The Battle of the Five Armies,120.965743,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",2014-12-10,956019788,144.0,7.1,4760,"[{""cast_id"": 10, ""character"": ""Bilbo Baggins"",...","[{""credit_id"": ""548ad49a9251414fa20011ab"", ""de..."
20,215000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1872, ""name"": ""loss of father""}, {""id""...",The Amazing Spider-Man,89.866276,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",2012-06-27,752215857,136.0,6.5,6586,"[{""cast_id"": 56, ""character"": ""Peter Parker / ...","[{""credit_id"": ""5395a60dc3a368641d004492"", ""de..."
21,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 4147, ""name"": ""robin hood""}, {""id"": 43...",Robin Hood,37.668301,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...",2010-05-12,310669540,140.0,6.2,1398,"[{""cast_id"": 1, ""character"": ""Robin Longstride...","[{""credit_id"": ""52fe43f2c3a368484e0076ad"", ""de..."
22,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""na...",The Hobbit: The Desolation of Smaug,94.370564,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",2013-12-11,958400000,161.0,7.6,4524,"[{""cast_id"": 3, ""character"": ""Bilbo Baggins"", ...","[{""credit_id"": ""52fe4926c3a36847f818b787"", ""de..."
23,180000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 392, ""name"": ""england""}, {""id"": 1461, ...",The Golden Compass,42.990906,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...",2007-12-04,372234864,113.0,5.8,1303,"[{""cast_id"": 43, ""character"": ""Lyra Belacqua"",...","[{""credit_id"": ""52fe4348c3a36847f8048635"", ""de..."
24,207000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...","[{""id"": 774, ""name"": ""film business""}, {""id"": ...",King Kong,61.226010,"[{""name"": ""WingNut Films"", ""id"": 11}, {""name"":...",2005-12-14,550000000,187.0,6.6,2337,"[{""cast_id"": 5, ""character"": ""Ann Darrow"", ""cr...","[{""credit_id"": ""52fe422ec3a36847f800a1d7"", ""de..."
25,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...","[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",Titanic,100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",1997-11-18,1845034188,194.0,7.5,7562,"[{""cast_id"": 20, ""character"": ""Rose DeWitt Buk...","[{""credit_id"": ""52fe425ac3a36847f8017985"", ""de..."
26,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...","[{""id"": 393, ""name"": ""civil war""}, {""id"": 6091...",Captain America: Civil War,198.372395,"[{""name"": ""Studio Babelsberg"", ""id"": 264}, {""n...",2016-04-27,1153304495,147.0,7.1,7241,"[{""cast_id"": 9, ""character"": ""Steve Rogers / C...","[{""credit_id"": ""569443d59251414b67000428"", ""de..."
27,209000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...","[{""id"": 1721, ""name"": ""fight""}, {""id"": 4410, ""...",Battleship,64.928382,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",2012-04-11,303025485,131.0,5.5,2114,"[{""cast_id"": 3, ""character"": ""Lieutenant Alex ...","[{""credit_id"": ""52fe469ec3a36847f8108d45"", ""de..."
28,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",Jurassic World,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...",2015-06-09,1513528810,124.0,6.5,8662,"[{""cast_id"": 10, ""character"": ""Owen Grady"", ""c...","[{""credit_id"": ""52fe4bf7c3a368484e1a0683"", ""de..."
29,200000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 4289, ""nam...",Skyfall,93.004993,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",2012-10-25,1108561013,143.0,6.9,7604,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""52fe46689251416c910537ad"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4773,27000,"[{""id"": 35, ""name"": ""Comedy""}]","[{""id"": 1361, ""name"": ""salesclerk""}, {""id"": 30...",Clerks,19.748658,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",1994-09-13,3151130,92.0,7.4,755,"[{""cast_id"": 7, ""character"": ""Dante Hicks"", ""c...","[{""credit_id"": ""52fe434ac3a36847f8049253"", ""de..."
4774,27000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...","[{""id"": 1566, ""name"": ""dream""}, {""id"": 13059, ...",Pink Narcissus,0.027811,"[{""name"": ""Strand Releasing"", ""id"": 3923}]",1971-01-01,0,64.0,6.0,9,"[{""cast_id"": 1006, ""character"": ""Pan"", ""credit...","[{""credit_id"": ""52fe4606c3a36847f80e7ed9"", ""de..."
4775,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...","[{""id"": 171993, ""name"": ""mumblecore""}]",Funny Ha Ha,0.362633,[],2002-09-20,76901,85.0,6.3,8,"[{""cast_id"": 1, ""character"": ""Marnie"", ""credit...","[{""credit_id"": ""52fe45309251416c9102a535"", ""de..."
4776,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 1438, ""name"": ""office""}, {""id"": 9673, ...",In the Company of Men,2.634007,"[{""name"": ""Alliance Atlantis Communications"", ...",1997-01-19,0,97.0,6.8,44,"[{""cast_id"": 1, ""character"": ""Chad"", ""credit_i...","[{""credit_id"": ""52fe46049251416c7506a36b"", ""de..."
4777,0,"[{""id"": 18, ""name"": ""Drama""}]",[],Manito,0.039264,[],2002-01-15,0,78.0,5.5,2,"[{""cast_id"": 1, ""character"": ""Junior Moreno"", ...","[{""credit_id"": ""54931bbf925141090e001d32"", ""de..."
4778,0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...","[{""id"": 10022, ""name"": ""rampage""}, {""id"": 1454...",Rampage,7.101197,"[{""name"": ""Boll Kino Beteiligungs GmbH & Co. K...",2009-08-14,0,85.0,6.0,131,"[{""cast_id"": 1, ""character"": ""Bill Williamson""...","[{""credit_id"": ""52fe46df9251416c91062979"", ""de..."
4779,0,"[{""id"": 35, ""name"": ""Comedy""}]","[{""id"": 305, ""name"": ""moon""}, {""id"": 490, ""nam...",Slacker,3.320622,[],1990-07-27,0,97.0,6.4,77,"[{""cast_id"": 1, ""character"": ""Should Have Stay...","[{""credit_id"": ""52fe45c49251416c75061c17"", ""de..."
4780,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 80, ""n...",[],Dutch Kills,0.038143,[],2015-10-02,0,90.0,0.0,0,"[{""cast_id"": 4, ""character"": ""Val"", ""credit_id...","[{""credit_id"": ""563d13ec9251414c70007d5e"", ""de..."
4781,22000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 13043, ""name"": ""dating""}, {""id"": 15160...",Dry Spell,0.048948,[],2013-02-14,0,90.0,6.0,1,"[{""cast_id"": 4, ""character"": ""Sasha"", ""credit_...","[{""credit_id"": ""52fe4ee39251416c911412e7"", ""de..."
4782,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10751, ""n...","[{""id"": 186, ""name"": ""christianity""}, {""id"": 4...",Flywheel,1.048524,[],2003-01-01,0,120.0,6.8,19,"[{""cast_id"": 1, ""character"": ""Jay"", ""credit_id...","[{""credit_id"": ""52fe471e9251416c7508e579"", ""de..."
4783,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...","[{""id"": 9712, ""name"": ""possession""}]",Backmask,3.619167,"[{""name"": ""GO Productions"", ""id"": 2943}, {""nam...",2015-01-16,0,91.0,4.7,79,"[{""cast_id"": 3, ""character"": ""Father Conway"", ...","[{""credit_id"": ""554c8351c3a3685e500041f5"", ""de..."
4784,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...","[{""id"": 171993, ""name"": ""mumblecore""}]",The Puffy Chair,1.243955,[],2005-01-17,0,85.0,6.2,15,"[{""cast_id"": 4, ""character"": ""Josh"", ""credit_i...","[{""credit_id"": ""52fe447fc3a368484e026881"", ""de..."
4785,0,"[{""id"": 18, ""name"": ""Drama""}]",[],Stories of Our Lives,0.327794,[],2014-09-05,0,60.0,0.0,0,"[{""cast_id"": 8, ""character"": """", ""credit_id"": ...","[{""credit_id"": ""549e790a9251414d27003096"", ""de..."
4786,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...","[{""id"": 10183, ""name"": ""independent film""}]",Breaking Upwards,0.674570,[],2009-03-14,0,88.0,5.6,12,"[{""cast_id"": 1, ""character"": ""Zoe"", ""credit_id...","[{""credit_id"": ""572239efc3a368712a0007db"", ""de..."
4787,0,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 9715, ""name"": ""superhero""}]",All Superheroes Must Die,3.545991,"[{""name"": ""Grindfest"", ""id"": 18818}]",2011-10-26,0,78.0,4.2,13,"[{""cast_id"": 1, ""character"": ""Charge / John"", ...","[{""credit_id"": ""52fe497f9251416c910af3d1"", ""de..."
4788,12000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 35, ""nam...","[{""id"": 237, ""name"": ""gay""}, {""id"": 900, ""name...",Pink Flamingos,4.553644,"[{""name"": ""Dreamland Productions"", ""id"": 407}]",1972-03-12,6000000,93.0,6.2,110,"[{""cast_id"": 8, ""character"": ""Divine / Babs Jo...","[{""credit_id"": ""52fe426bc3a36847f801d203"", ""de..."
4789,0,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 6782, ""name"": ""addiction""}, {""id"": 155...",Clean,1.464566,[],2004-09-01,0,111.0,6.7,17,"[{""cast_id"": 1, ""character"": ""Emily Wang"", ""cr...","[{""credit_id"": ""52fe47369251416c9106db9b"", ""de..."
4790,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10769, ""n...",[],دایره,1.193779,"[{""name"": ""Jafar Panahi Film Productions"", ""id...",2000-09-08,0,90.0,6.6,17,"[{""cast_id"": 3, ""character"": ""Nargess"", ""credi...","[{""credit_id"": ""52fe45b09251416c7505f189"", ""de..."
4791,13,"[{""id"": 27, ""name"": ""Horror""}]","[{""id"": 14903, ""name"": ""home invasion""}]",Tin Can Man,0.332679,"[{""name"": ""Park Films"", ""id"": 21871}, {""name"":...",2007-01-01,0,84.0,2.0,1,"[{""cast_id"": 1, ""character"": ""Dave"", ""credit_i...","[{""credit_id"": ""54c7851b925141679100372a"", ""de..."
4792,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...","[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",キュア,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]",1997-11-06,99000,111.0,7.4,63,"[{""cast_id"": 3, ""character"": ""Kenichi Takabe"",...","[{""credit_id"": ""52fe45cc9251416c9103eb7b"", ""de..."
4793,0,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 718, ""name"": ""confession""}, {""id"": 100...",On The Downlow,0.029757,"[{""name"": ""Iconoclast Films"", ""id"": 26677}]",2004-04-11,0,90.0,6.0,2,"[{""cast_id"": 1, ""character"": ""Isaac"", ""credit_...","[{""credit_id"": ""548c416392514122ef00197d"", ""de..."
4794,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 27, ""n...",[],Sanctuary: Quite a Conundrum,0.166513,"[{""name"": ""Gold Lion Films"", ""id"": 37870}, {""n...",2012-01-20,0,82.0,0.0,0,"[{""cast_id"": 3, ""character"": ""Mimi"", ""credit_i...","[{""credit_id"": ""545f8107c3a3686cbb0041fd"", ""de..."
4795,0,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 10726, ""name"": ""gang""}, {""id"": 33928, ...",Bang,0.918116,"[{""name"": ""Asylum Films"", ""id"": 10571}, {""name...",1995-09-09,0,98.0,6.0,1,"[{""cast_id"": 2, ""character"": ""The Girl"", ""cred...","[{""credit_id"": ""52fe4ab0c3a368484e161add"", ""de..."
4796,7000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...","[{""id"": 1448, ""name"": ""distrust""}, {""id"": 2101...",Primer,23.307949,"[{""name"": ""Thinkfilm"", ""id"": 446}]",2004-10-08,424760,77.0,6.9,658,"[{""cast_id"": 1, ""character"": ""Aaron"", ""credit_...","[{""credit_id"": ""52fe45e79251416c75066791"", ""de..."
4797,0,"[{""id"": 10769, ""name"": ""Foreign""}, {""id"": 53, ...",[],Cavite,0.022173,[],2005-03-12,0,80.0,7.5,2,[],"[{""credit_id"": ""52fe475dc3a368484e0c319f"", ""de..."
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",1992-09-04,2040920,81.0,6.6,238,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],Newlyweds,0.642552,[],2011-12-26,0,85.0,5.9,5,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",2013-10-13,0,120.0,7.0,6,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."

In [39]:
# converte
converte_columns = ["genres", "keywords", "production_companies", "crew", "cast"]
for columns in converte_columns:
    movie_credit[columns] = movie_credit[columns].apply
'''    
def get_names(keywords):
    return ",".join(x["name"] for x in keywords)

#cast
movie_credit["cast"] = movie_credit["cast"].apply(get_names)

#genres
movie_credit["genres"] = movie_credit["genres"].apply(get_names)

#keywords
movie_credit["keywords"] = movie_credit["keywords"].apply(get_names)

#production_companies
movie_credit["production_companies"] = movie_credit["production_companies"].apply(get_names)

#crew -> director
def director(x):
    for i in x:
        if i["job"] == "Director":
            return i["name"]
        
movie_credit["crew"] = movie_credit["crew"].apply(director)

'''

TypeError:          budget                                     genres  \
0     237000000   Action,Adventure,Fantasy,Science Fiction
1     300000000                   Adventure,Fantasy,Action
2     245000000                     Action,Adventure,Crime
3     250000000                Action,Crime,Drama,Thriller
4     260000000           Action,Adventure,Science Fiction
5     258000000                   Fantasy,Action,Adventure
6     260000000                           Animation,Family
7     280000000           Action,Adventure,Science Fiction
8     250000000                   Adventure,Fantasy,Family
9     250000000                   Action,Adventure,Fantasy
10    270000000   Adventure,Fantasy,Action,Science Fiction
11    200000000            Adventure,Action,Thriller,Crime
12    200000000                   Adventure,Fantasy,Action
13    255000000                   Action,Adventure,Western
14    225000000   Action,Adventure,Fantasy,Science Fiction
15    225000000                   Adventure,Family,Fantasy
16    220000000           Science Fiction,Action,Adventure
17    380000000                   Adventure,Action,Fantasy
18    225000000              Action,Comedy,Science Fiction
19    250000000                   Action,Adventure,Fantasy
20    215000000                   Action,Adventure,Fantasy
21    200000000                           Action,Adventure
22    250000000                          Adventure,Fantasy
23    180000000                          Adventure,Fantasy
24    207000000                     Adventure,Drama,Action
25    200000000                     Drama,Romance,Thriller
26    250000000           Adventure,Action,Science Fiction
27    209000000  Thriller,Action,Adventure,Science Fiction
28    150000000  Action,Adventure,Science Fiction,Thriller
29    200000000                  Action,Adventure,Thriller
...         ...                                        ...
4773      27000                                     Comedy
4774      27000                              Drama,Romance
4775          0                               Drama,Comedy
4776          0                               Comedy,Drama
4777          0                                      Drama
4778          0                Action,Drama,Crime,Thriller
4779          0                                     Comedy
4780          0                       Thriller,Crime,Drama
4781      22000                             Comedy,Romance
4782          0                               Drama,Family
4783          0                            Thriller,Horror
4784          0                       Drama,Comedy,Romance
4785          0                                      Drama
4786          0                             Comedy,Romance
4787          0                   Science Fiction,Thriller
4788      12000                        Horror,Comedy,Crime
4789          0                                      Drama
4790          0                              Drama,Foreign
4791         13                                     Horror
4792      20000              Crime,Horror,Mystery,Thriller
4793          0                                      Drama
4794          0                     Thriller,Horror,Comedy
4795          0                                      Drama
4796       7000             Science Fiction,Drama,Thriller
4797          0                           Foreign,Thriller
4798     220000                      Action,Crime,Thriller
4799       9000                             Comedy,Romance
4800          0              Comedy,Drama,Romance,TV Movie
4801          0
4802          0                                Documentary

                                               keywords  \
0     culture clash,future,space war,space colony,so...
1     ocean,drug abuse,exotic island,east india trad...
2     spy,based on novel,secret agent,sequel,mi6,bri...
3     dc comics,crime fighter,terrorist,secret ident...
4     based on novel,mars,medallion,space travel,pri...
5     dual identity,amnesia,sandstorm,love of one's ...
6     hostage,magic,horse,fairy tale,musical,princes...
7     marvel comic,sequel,superhero,based on comic b...
8     witch,magic,broom,school of witchcraft,wizardr...
9     dc comics,vigilante,superhero,based on comic b...
10    saving the world,dc comics,invulnerability,seq...
11    killing,undercover,secret agent,british secret...
12    witch,fortune teller,bondage,exotic island,mon...
13    texas,horse,survivor,texas ranger,partner,outl...
14    saving the world,dc comics,superhero,based on ...
15    based on novel,fictional place,brother sister ...
16    new york,shield,marvel comic,superhero,based o...
17    sea,captain,mutiny,sword,prime minister,sailin...
18    time travel,time machine,alien,fictional gover...
19    corruption,elves,dwarves,orcs,middle-earth (to...
20    loss of father,vigilante,serum,marvel comic,sc...
21    robin hood,archer,knight,sherwood forest,bow a...
22    elves,dwarves,orcs,hobbit,dragon,wizard,sword ...
23    england,compass,experiment,lordship,uncle,pola...
24    film business,screenplay,show business,film ma...
25    shipwreck,iceberg,ship,panic,titanic,ocean lin...
26    civil war,war,marvel comic,sequel,superhero,ba...
27    fight,u.s. navy,mind reading,hong kong,soccer,...
28    monster,dna,tyrannosaurus rex,velociraptor,isl...
29    spy,secret agent,sociopath,killer,art gallery,...
...                                                 ...
4773               salesclerk,loser,aftercreditsstinger
4774                                 dream,prostitution
4775                                         mumblecore
4776  office,love,independent film,secretary,misogynist
4777
4778                     rampage,massacre,killing spree
4779  moon,philosophy,burglar,texas,dream,atomic bom...
4780
4781  dating,divorce,sex scene,sex comedy,anti roman...
4782  christianity,father son relationship,georgia,a...
4783                                         possession
4784                                         mumblecore
4785
4786                                   independent film
4787                                          superhero
4788  gay,trailer park,pop culture,drug dealer,heroi...
4789     addiction,recovering drug addict,estranged son
4790
4791                                      home invasion
4792  japan,prostitute,hotel,based on novel,hallucin...
4793  confession,hazing,gang member,latino,lgbt,cath...
4794
4795         gang,audition,police fake,homeless,actress
4796  distrust,garage,identity crisis,time travel,ti...
4797
4798  united states–mexico barrier,legs,arms,paper k...
4799
4800  date,love at first sight,narration,investigati...
4801
4802               obsession,camcorder,crush,dream girl

                                   original_title  popularity  \
0                                          Avatar  150.437577
1        Pirates of the Caribbean: At World's End  139.082615
2                                         Spectre  107.376788
3                           The Dark Knight Rises  112.312950
4                                     John Carter   43.926995
5                                    Spider-Man 3  115.699814
6                                         Tangled   48.681969
7                         Avengers: Age of Ultron  134.279229
8          Harry Potter and the Half-Blood Prince   98.885637
9              Batman v Superman: Dawn of Justice  155.790452
10                               Superman Returns   57.925623
11                              Quantum of Solace  107.928811
12     Pirates of the Caribbean: Dead Man's Chest  145.847379
13                                The Lone Ranger   49.046956
14                                   Man of Steel   99.398009
15       The Chronicles of Narnia: Prince Caspian   53.978602
16                                   The Avengers  144.448633
17    Pirates of the Caribbean: On Stranger Tides  135.413856
18                                 Men in Black 3   52.035179
19      The Hobbit: The Battle of the Five Armies  120.965743
20                         The Amazing Spider-Man   89.866276
21                                     Robin Hood   37.668301
22            The Hobbit: The Desolation of Smaug   94.370564
23                             The Golden Compass   42.990906
24                                      King Kong   61.226010
25                                        Titanic  100.025899
26                     Captain America: Civil War  198.372395
27                                     Battleship   64.928382
28                                 Jurassic World  418.708552
29                                        Skyfall   93.004993
...                                           ...         ...
4773                                       Clerks   19.748658
4774                               Pink Narcissus    0.027811
4775                                  Funny Ha Ha    0.362633
4776                        In the Company of Men    2.634007
4777                                       Manito    0.039264
4778                                      Rampage    7.101197
4779                                      Slacker    3.320622
4780                                  Dutch Kills    0.038143
4781                                    Dry Spell    0.048948
4782                                     Flywheel    1.048524
4783                                     Backmask    3.619167
4784                              The Puffy Chair    1.243955
4785                         Stories of Our Lives    0.327794
4786                             Breaking Upwards    0.674570
4787                     All Superheroes Must Die    3.545991
4788                               Pink Flamingos    4.553644
4789                                        Clean    1.464566
4790                                        دایره    1.193779
4791                                  Tin Can Man    0.332679
4792                                          キュア    0.212443
4793                               On The Downlow    0.029757
4794                 Sanctuary: Quite a Conundrum    0.166513
4795                                         Bang    0.918116
4796                                       Primer   23.307949
4797                                       Cavite    0.022173
4798                                  El Mariachi   14.269792
4799                                    Newlyweds    0.642552
4800                    Signed, Sealed, Delivered    1.444476
4801                             Shanghai Calling    0.857008
4802                            My Date with Drew    1.929883

                                   production_companies release_date  \
0     Ingenious Film Partners,Twentieth Century Fox ...   2009-12-10
1     Walt Disney Pictures,Jerry Bruckheimer Films,S...   2007-05-19
2                          Columbia Pictures,Danjaq,B24   2015-10-26
3     Legendary Pictures,Warner Bros.,DC Entertainme...   2012-07-16
4                                  Walt Disney Pictures   2012-03-07
5     Columbia Pictures,Laura Ziskin Productions,Mar...   2007-05-01
6     Walt Disney Pictures,Walt Disney Animation Stu...   2010-11-24
7     Marvel Studios,Prime Focus,Revolution Sun Studios   2015-04-22
8                             Warner Bros.,Heyday Films   2009-07-07
9     DC Comics,Atlas Entertainment,Warner Bros.,DC ...   2016-03-23
10    DC Comics,Legendary Pictures,Warner Bros.,Bad ...   2006-06-28
11                                      Eon Productions   2008-10-30
12    Walt Disney Pictures,Jerry Bruckheimer Films,S...   2006-06-20
13    Walt Disney Pictures,Jerry Bruckheimer Films,I...   2013-07-03
14    Legendary Pictures,Warner Bros.,DC Entertainme...   2013-06-12
15    Walt Disney,Walden Media,Stillking Films,Ozumi...   2008-05-15
16                    Paramount Pictures,Marvel Studios   2012-04-25
17    Walt Disney Pictures,Jerry Bruckheimer Films,M...   2011-05-14
18    Amblin Entertainment,Media Magik Entertainment...   2012-05-23
19    WingNut Films,New Line Cinema,Warner Bros. Pic...   2014-12-10
20    Columbia Pictures,Laura Ziskin Productions,Mar...   2012-06-27
21    Imagine Entertainment,Universal Pictures,Scott...   2010-05-12
22    WingNut Films,New Line Cinema,Warner Bros. Pic...   2013-12-11
23    New Line Cinema,Ingenious Film Partners,Depth ...   2007-12-04
24    WingNut Films,Universal Pictures,Big Primate P...   2005-12-14
25    Paramount Pictures,Twentieth Century Fox Film ...   1997-11-18
26    Studio Babelsberg,Marvel Studios,Walt Disney S...   2016-04-27
27    Universal Pictures,Hasbro,Bluegrass Films,Film 44   2012-04-11
28    Universal Studios,Amblin Entertainment,Legenda...   2015-06-09
29                                    Columbia Pictures   2012-10-25
...                                                 ...          ...
4773               Miramax Films,View Askew Productions   1994-09-13
4774                                   Strand Releasing   1971-01-01
4775                                                      2002-09-20
4776  Alliance Atlantis Communications,Fair and Squa...   1997-01-19
4777                                                      2002-01-15
4778  Boll Kino Beteiligungs GmbH & Co. KG,Brightlig...   2009-08-14
4779                                                      1990-07-27
4780                                                      2015-10-02
4781                                                      2013-02-14
4782                                                      2003-01-01
4783  GO Productions,Vicarious Entertainment,Bloodli...   2015-01-16
4784                                                      2005-01-17
4785                                                      2014-09-05
4786                                                      2009-03-14
4787                                          Grindfest   2011-10-26
4788                              Dreamland Productions   1972-03-12
4789                                                      2004-09-01
4790                      Jafar Panahi Film Productions   2000-09-08
4791                      Park Films,Camera Stylo Films   2007-01-01
4792                                      Daiei Studios   1997-11-06
4793                                   Iconoclast Films   2004-04-11
4794               Gold Lion Films,T-Street Productions   2012-01-20
4795  Asylum Films,FM Entertainment,Eagle Eye Films ...   1995-09-09
4796                                          Thinkfilm   2004-10-08
4797                                                      2005-03-12
4798                                  Columbia Pictures   1992-09-04
4799                                                      2011-12-26
4800  Front Street Pictures,Muse Entertainment Enter...   2013-10-13
4801                                                      2012-05-03
4802          rusty bear entertainment,lucky crow films   2005-08-05

         revenue  runtime  vote_average  vote_count  \
0     2787965087    162.0           7.2       11800
1      961000000    169.0           6.9        4500
2      880674609    148.0           6.3        4466
3     1084939099    165.0           7.6        9106
4      284139100    132.0           6.1        2124
5      890871626    139.0           5.9        3576
6      591794936    100.0           7.4        3330
7     1405403694    141.0           7.3        6767
8      933959197    153.0           7.4        5293
9      873260194    151.0           5.7        7004
10     391081192    154.0           5.4        1400
11     586090727    106.0           6.1        2965
12    1065659812    151.0           7.0        5246
13      89289910    149.0           5.9        2311
14     662845518    143.0           6.5        6359
15     419651413    150.0           6.3        1630
16    1519557910    143.0           7.4       11776
17    1045713802    136.0           6.4        4948
18     624026776    106.0           6.2        4160
19     956019788    144.0           7.1        4760
20     752215857    136.0           6.5        6586
21     310669540    140.0           6.2        1398
22     958400000    161.0           7.6        4524
23     372234864    113.0           5.8        1303
24     550000000    187.0           6.6        2337
25    1845034188    194.0           7.5        7562
26    1153304495    147.0           7.1        7241
27     303025485    131.0           5.5        2114
28    1513528810    124.0           6.5        8662
29    1108561013    143.0           6.9        7604
...          ...      ...           ...         ...
4773     3151130     92.0           7.4         755
4774           0     64.0           6.0           9
4775       76901     85.0           6.3           8
4776           0     97.0           6.8          44
4777           0     78.0           5.5           2
4778           0     85.0           6.0         131
4779           0     97.0           6.4          77
4780           0     90.0           0.0           0
4781           0     90.0           6.0           1
4782           0    120.0           6.8          19
4783           0     91.0           4.7          79
4784           0     85.0           6.2          15
4785           0     60.0           0.0           0
4786           0     88.0           5.6          12
4787           0     78.0           4.2          13
4788     6000000     93.0           6.2         110
4789           0    111.0           6.7          17
4790           0     90.0           6.6          17
4791           0     84.0           2.0           1
4792       99000    111.0           7.4          63
4793           0     90.0           6.0           2
4794           0     82.0           0.0           0
4795           0     98.0           6.0           1
4796      424760     77.0           6.9         658
4797           0     80.0           7.5           2
4798     2040920     81.0           6.6         238
4799           0     85.0           5.9           5
4800           0    120.0           7.0           6
4801           0     98.0           5.7           7
4802           0     90.0           6.3          16

                                                   cast                crew
0     Sam Worthington,Zoe Saldana,Sigourney Weaver,S...       James Cameron
1     Johnny Depp,Orlando Bloom,Keira Knightley,Stel...      Gore Verbinski
2     Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...          Sam Mendes
3     Christian Bale,Michael Caine,Gary Oldman,Anne ...   Christopher Nolan
4     Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...      Andrew Stanton
5     Tobey Maguire,Kirsten Dunst,James Franco,Thoma...           Sam Raimi
6     Zachary Levi,Mandy Moore,Donna Murphy,Ron Perl...        Byron Howard
7     Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo...         Joss Whedon
8     Daniel Radcliffe,Rupert Grint,Emma Watson,Tom ...         David Yates
9     Ben Affleck,Henry Cavill,Gal Gadot,Amy Adams,J...         Zack Snyder
10    Brandon Routh,Kevin Spacey,Kate Bosworth,James...        Bryan Singer
11    Daniel Craig,Olga Kurylenko,Mathieu Amalric,Ju...        Marc Forster
12    Johnny Depp,Orlando Bloom,Keira Knightley,Stel...      Gore Verbinski
13    Johnny Depp,Armie Hammer,William Fichtner,Hele...      Gore Verbinski
14    Henry Cavill,Amy Adams,Michael Shannon,Kevin C...         Zack Snyder
15    Ben Barnes,William Moseley,Anna Popplewell,Ska...      Andrew Adamson
16    Robert Downey Jr.,Chris Evans,Mark Ruffalo,Chr...         Joss Whedon
17    Johnny Depp,Penélope Cruz,Ian McShane,Kevin Mc...        Rob Marshall
18    Will Smith,Tommy Lee Jones,Josh Brolin,Michael...    Barry Sonnenfeld
19    Martin Freeman,Ian McKellen,Richard Armitage,K...       Peter Jackson
20    Andrew Garfield,Emma Stone,Rhys Ifans,Denis Le...           Marc Webb
21    Russell Crowe,Cate Blanchett,Max von Sydow,Wil...        Ridley Scott
22    Martin Freeman,Ian McKellen,Richard Armitage,K...       Peter Jackson
23    Dakota Blue Richards,Nicole Kidman,Daniel Crai...         Chris Weitz